name: prm2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  pinput: ^4.0.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  image_picker: ^1.2.0
  textfield_tags: ^3.0.1
  file_picker: ^10.3.3
  http_parser: ^4.0.2
  http: ^1.2.1
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  # Audio playback with background support
  just_audio: ^0.9.40
  just_audio_background: ^0.0.1-beta.13
  audio_service: ^0.18.15
  # Image caching
  cached_network_image: ^3.4.1
  # File caching (for audio persistence)
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.4
  # State management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
